name: Run Tests & Coverage
 
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v3
     
      - name: Build Docker Image
        run: docker build -t fizzbuzz-app .
     
      - name: Run Tests inside Docker
        run: docker run fizzbuzz-app pytest --cov=fizzbuzz --cov-report=term-missing tests/

      - name: Generate Coverage Report
        run: docker run fizzbuzz-app pytest --cov=fizzbuzz --cov-report=html tests/

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
 
  pr-validation:
    needs: test  
    runs-on: ubuntu-latest
    steps:
      - name: Check Test Status
        if: ${{ needs.test.result != 'success' }}
        run: |
          echo "❌ Les tests ont échoué, la PR ne peut pas être fusionnée."
          exit 1  # Force l'échec du workflow si les tests échouent

      - name: Validate PR
        if: ${{ needs.test.result == 'success' }}
        run: echo "✅ Tests passed! PR can be merged."
