name: Auto-Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  auto-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install linting tools
        run: |
          pip install black isort flake8

      - name: Auto-correct style with Black
        run: |
          echo "Lancement du formatage automatique Black..."
          black .

      - name: Auto-correct imports with isort
        run: |
          echo "Lancement du formatage automatique isort..."
          isort .

      - name: Check code with Flake8
        run: |
          echo "Analyse Flake8..."
          flake8 .
      
      - name: Commit and push changes
        run: |
          # Configure l'identité du commit
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Vérifie s'il y a des changements après le formatage
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "style: auto-lint code"
            git push
          else
            echo "Aucun changement détecté, rien à pousser."
          fi
