name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # vous pouvez préciser 3.8, 3.10, etc.

      - name: Install dependencies
        # Si vous n'avez pas de requirements.txt, vous pouvez ignorer cette étape
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        # Remplacez 'pytest test' par la commande que vous utilisez pour lancer vos tests
        # Par exemple: python -m unittest discover -s test
        run: |
          pip install pytest
          pytest test
